# This file was generated by GoReleaser. DO NOT EDIT.
cask "omni-on-unraid" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "45cce5f2257637cb9b863c2f88051ea76cbe1535fefd3baad0f45017aa14eeba"
      url "https://github.com/syscode-labs/omni-on-unraid/releases/download/v#{version}/omni-on-unraid_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "28d29cdcf4e9df58d9f5f2e6c2096b7472a3079741c92cfd77fe4dff1a83339a"
      url "https://github.com/syscode-labs/omni-on-unraid/releases/download/v#{version}/omni-on-unraid_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "213cfb4006553d9add6a73a0ecf02580b40efbe4ee2046dc01cdc974a1cd7cd8"
      url "https://github.com/syscode-labs/omni-on-unraid/releases/download/v#{version}/omni-on-unraid_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a76449e8cb885cf383606752a5f80db666923cda12b5c5f084a2c167671ad0fb"
      url "https://github.com/syscode-labs/omni-on-unraid/releases/download/v#{version}/omni-on-unraid_#{version}_linux_arm64.tar.gz"
    end
  end

  name "omni-on-unraid"
  desc "Operator TUI for Omni-on-Unraid"
  homepage "https://github.com/syscode-labs/omni-on-unraid"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "omni-on-unraid"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/omni-on-unraid"]
    end
  end

  # No zap stanza required

end
