# This file was generated by GoReleaser. DO NOT EDIT.
cask "omni-on-unraid" do
  version "0.2.1"

  on_macos do
    on_intel do
      sha256 "9a83ae7edbc3965600356c7ed6eb650851e2a8bc81def78c8e28315d3776812b"
      url "https://github.com/syscode-labs/omni-on-unraid/releases/download/v#{version}/omni-on-unraid_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "726e430287e78caee6f15e0e9d4962d537a22852a540bbfa9b343b598b6b0326"
      url "https://github.com/syscode-labs/omni-on-unraid/releases/download/v#{version}/omni-on-unraid_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "fda790b70687dfe81e329b7738656a9c33dbd3746780da6246574305f4077697"
      url "https://github.com/syscode-labs/omni-on-unraid/releases/download/v#{version}/omni-on-unraid_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "1a2fca8b4877e363e60fd99a7ae8cf7235ebf367ab20bc1c6fdb2183f38e65b6"
      url "https://github.com/syscode-labs/omni-on-unraid/releases/download/v#{version}/omni-on-unraid_#{version}_linux_arm64.tar.gz"
    end
  end

  name "omni-on-unraid"
  desc "Operator TUI for Omni-on-Unraid"
  homepage "https://github.com/syscode-labs/omni-on-unraid"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "omni-on-unraid"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/omni-on-unraid"]
    end
  end

  # No zap stanza required

end
